version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha
      MYSQL_DATABASE: curva_crescimento
      MYSQL_USER: user
      MYSQL_PASSWORD: sua_senha
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local